name: Hello GitHub Actions
on: push
jobs:
  Example-Actions-Job:
    name: Figgurin GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Echo some text message
      - run: echo "This is an echo message."

      # This was the event
      - run: echo "This is the event name -> ${{ github.event_name }} "
      
      # Runner information
      - run: echo "This job is the OS ${{ runner.os }}"
      
      # Information about the repository and branch
      - run: echo " Here's some repo info. branch ${{ github.ref }} repo ${{ github.repository }}."
      
      # Use Action located in https://github.com/actions
      - name: Check out repository code
        uses: actions/checkout@v2  
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."
      
      - run: echo "The workflow is now ready to test your code on the runner."
      
      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      
      - name: Display dotnet 
        run: dotnet --version
      
      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
      
      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}
      
      - run: echo "This job's status is ${{ job.status }}."

  Second-Job:
    name: The second job running on another runner
    runs-on: windows-latest
    needs: Example-Actions-Job
    steps:
      - run: echo "This is another job on a different server -> ${{ runner.os }}."


# Notes

# like Xml or JSON   Isn't normal written by machines

# Key value pairs   Can use quotes but not requred

# the key is always a string
# the value can be object, coolectioion or 

#  The indent hierarchy is defined with TWO SPACES
#  DON'T use TABS to indent
