name: Hello GitHub Actions
on: push
jobs:
  Example-Actions-Job:
    name: Figgurin GitHub Actions
    runs-on: ubuntu-latest
    steps:
      # Echo some text message
      - run: echo "This is an echo message."

      # run a linux command
      - run: ls -a
      
      
      # run a linux command
      - run: ls /etc


      # run a linux command
      - run: pwd 

      # Here is an echo of a context. Notice the dollar sign, and double curly braces
      - run: echo "context ${{github.event_name}}"
      
# Notes

# like Xml or JSON   Isn't normal written by machines

# Key value pairs   Can use quotes but not requred

# the key is always a string
# the value can be object, coolectioion or 

#  The indent hierarchy is defined with TWO SPACES
#  DON'T use TABS to indent
